# Generated by Django 3.2.4 on 2021-07-17 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_auto_20210716_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_title', models.CharField(max_length=30)),
                ('coupon_limit', models.IntegerField()),
                ('coupon_offer', models.FloatField()),
                ('coupon_start', models.DateField()),
                ('coupon_end', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='offer_price',
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='offer',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='CouponUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
