# Generated by Django 3.2.4 on 2021-07-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210717_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
