# Generated by Django 3.2.4 on 2021-07-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_coupon_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponused',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='couponused',
            name='order_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
