# Generated by Django 3.2.4 on 2021-07-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210717_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
