# Generated by Django 3.2.4 on 2021-07-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_count',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
