# Generated by Django 3.2.4 on 2021-07-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_referral_referral_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral_control',
            name='referral_amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='referral_control',
            name='referral_percentage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='referral_control',
            name='referral_percentage_limit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='referral_control',
            name='referral_user_limit',
            field=models.CharField(max_length=50),
        ),
    ]
