# Generated by Django 3.2.4 on 2021-07-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_auto_20210720_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral_control',
            name='referral_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='referral_control',
            name='referral_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='referral_control',
            name='referral_percentage_limit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
