# Generated by Django 3.2.4 on 2021-07-21 03:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referral', '0005_referral_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='referral_control',
            new_name='ReferralControl',
        ),
        migrations.RenameModel(
            old_name='referral_code',
            new_name='ReferralUsers',
        ),
    ]
