# Generated by Django 3.2.4 on 2021-07-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0006_auto_20210721_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralusers',
            name='referral_count',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
