# Generated by Django 3.2.4 on 2021-07-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0010_rename_referral_end_referralcontrol_referral_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcontrol',
            name='referral_percentage',
        ),
        migrations.RemoveField(
            model_name='referralcontrol',
            name='referral_percentage_limit',
        ),
    ]
