# Generated by Django 3.2.4 on 2021-07-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0011_auto_20210722_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='is_ordered_recommended_user',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='is_ordered_user',
        ),
        migrations.AddField(
            model_name='referralcoupon',
            name='order_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
