# Generated by Django 3.2.4 on 2021-07-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0012_auto_20210723_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcoupon',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
