# Generated by Django 3.2.4 on 2021-07-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0013_referralcoupon_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='discount_amount',
            field=models.CharField(default=200, max_length=50),
        ),
    ]
