# Generated by Django 3.2.4 on 2021-07-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0014_referral_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='referralcoupon',
            name='discount_amount',
            field=models.CharField(default=200, max_length=50),
        ),
    ]
