# Generated by Django 3.2.4 on 2021-07-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0015_auto_20210723_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcoupon',
            name='discount_amount',
            field=models.CharField(max_length=50),
        ),
    ]
