# Generated by Django 3.2.4 on 2021-07-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer_percentage',
            field=models.IntegerField(null=True),
        ),
    ]
