# Generated by Django 3.2.4 on 2021-07-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
